using DotNetEd.CoreAdmin.DemoAppDotNet6.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetEd.CoreAdmin.DemoApp.Models
{
    public class TestDbContext : DbContext
    {
        public DbSet<TestEntity> TestEntities { get; set; }

        public DbSet<TestAutogeneratedKeyEntity> TestAutogeneratedKeyEntities { get; set; }

        public DbSet<TestEntityWithImage> TestEntitiesWithImages { get; set; }

        public DbSet<TestParentEntity> TestParentEntities { get; set; }

        public DbSet<TestChildEntity> TestChildEntities { get; set; }

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public TestDbContext(DbContextOptions<TestDbContext> contextOptions) : base(contextOptions)
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        {
            this.Database.EnsureCreated();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var seedData = new List<TestEntity>();
            foreach(var i in Enumerable.Range(0, 2000))
            {
                seedData.Add(new TestEntity() { Id = Guid.NewGuid(), Name = "Test entity " + i, Title = "Test title " + i, Price = new Random().NextDouble() });
            }

            modelBuilder.Entity<TestEntity>().HasData(seedData);

            var seedDataImages = new List<TestEntityWithImage>();

            seedDataImages.Add(new TestEntityWithImage() { Id = Guid.NewGuid(), Name = "Handsome person", Image = System.IO.File.ReadAllBytes("DemoAssets/ed-100.png") });
        
            modelBuilder.Entity<TestEntityWithImage>().HasData(seedDataImages);

            var seedDataChildren = new List<TestChildEntity>();
            foreach (var i in Enumerable.Range(0, 10))
            {
                seedDataChildren.Add(new TestChildEntity() { Id = Guid.NewGuid(), Name = "Child entity " + i });
            }
            modelBuilder.Entity<TestChildEntity>().HasData(seedDataChildren);

            var seedDataParents = new List<TestParentEntity>();
            seedDataParents.Add(new TestParentEntity() { ParentId = Guid.NewGuid(), ChildId = seedDataChildren.First().Id });
            modelBuilder.Entity<TestParentEntity>().HasData(seedDataParents);

            
        }
    }
}
