using DotNetEd.CoreAdmin.IntegrationTests.TestApp.Entities;
using Microsoft.EntityFrameworkCore;

namespace DotNetEd.CoreAdmin.IntegrationTests.TestApp
{
    public class IntegrationTestDbContext : DbContext
    {
        public DbSet<TestEntity> TestEntities { get; set; }

        public DbSet<TestAutogeneratedKeyEntity> TestAutogeneratedKeyEntities { get; set; }

        public IntegrationTestDbContext(DbContextOptions<IntegrationTestDbContext> contextOptions) : base(contextOptions)
        {

        }
    }
}
