using System;
using System.Collections.Generic;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

using DotNetEd.CoreAdmin.IntegrationTests.TestApp.Entities;


namespace DotNetEd.CoreAdmin.IntegrationTests
{
    public class OptionsTests : IClassFixture<TestAppFixture>
    {
        private readonly TestAppFixture _fixture;

        public OptionsTests(TestAppFixture fixture)
        {
            _fixture = fixture;
        }

        static void ConfigureTestServices(IServiceCollection services) { }

        [Fact]
        public async Task ReturnsBuiltInAssetPathWhenCdnOptionsNotSet()
        {
            // Arrange
            var client = _fixture.Factory.WithWebHostBuilder(builder => {
                builder.UseEnvironment("Development");
                builder.ConfigureTestServices(ConfigureTestServices);
            }).CreateClient();

            // Act
            var response = await client.GetAsync("/coreadmin");

            // Assert
            Assert.True(response.StatusCode == System.Net.HttpStatusCode.OK);

            var pageContent = await response.Content.ReadAsStringAsync();

            Assert.Contains("<link rel=\"stylesheet\" class=\"meta-css-light\" href=\"/_content/CoreAdmin/css/bootstrap.min.css\" media=\"(prefers-color-scheme: no-preference), (prefers-color-scheme: light)\" />", pageContent);
            Assert.Contains("<link rel=\"stylesheet\" class=\"meta-css-dark\" href=\"/_content/CoreAdmin/css/bootstrap-dark.min.css\" media=\"(prefers-color-scheme: dark)\" />", pageContent);
        }

        static void ConfigureTestServicesWithOptionsIgnoringDbSets(IServiceCollection services, IEnumerable<Type> dbSetsToIgnore)
        {
            services.AddCoreAdmin(new CoreAdminOptions() { IgnoreEntityTypes = dbSetsToIgnore });
        }

        [Fact] public async Task IgnoreEntityTypes_DoesNotIncludeIgnoredDbSets()
        {
            // Arrange
            var client = _fixture.Factory.WithWebHostBuilder(builder => {
                builder.UseEnvironment("Development");
                builder.ConfigureTestServices(services =>
                        ConfigureTestServicesWithOptionsIgnoringDbSets(services,
                        new List<Type> { typeof(TestAutogeneratedKeyEntity) }));
            }).CreateClient();

            // Act
            var response = await client.GetAsync("/coreadmindata/index/TestAutogeneratedKeyEntities");

            Assert.False(response.IsSuccessStatusCode);
            Assert.Equal(System.Net.HttpStatusCode.NotFound, response.StatusCode);

        }

        [Fact]
        public async Task ReturnsCdnAssetPathWhenCdnOptionsSet()
        {
            var cdnPath = "https://wow-an-amazing-cdn.com/assets";

            // Arrange
            var client = _fixture.Factory.WithWebHostBuilder(builder => {
                builder.UseEnvironment("Development");
                builder.ConfigureTestServices(ConfigureTestServices);
                builder.Configure(
                        app =>
                        {
                            app.UseRouting();
                            app.UseCoreAdminCdn(cdnPath);
                            app.UseEndpoints(endpoints =>
                            {
                                endpoints.MapControllerRoute(
                                    name: "default",
                                    pattern: "{controller=Home}/{action=Index}/{id?}");

                            });
                        }
                    );
            }).CreateClient();

            // Act
            var response = await client.GetAsync("/coreadmin");

            // Assert
            Assert.True(response.StatusCode == System.Net.HttpStatusCode.OK);

            var pageContent = await response.Content.ReadAsStringAsync();

            Assert.Contains("<link rel=\"stylesheet\" class=\"meta-css-light\" href=\"" + cdnPath + "/css/bootstrap.min.css\" media=\"(prefers-color-scheme: no-preference), (prefers-color-scheme: light)\" />", pageContent);
            Assert.Contains("<link rel=\"stylesheet\" class=\"meta-css-dark\" href=\"" + cdnPath + "/css/bootstrap-dark.min.css\" media=\"(prefers-color-scheme: dark)\" />", pageContent);
        }


    }
}
